extends Node
## Registers movement input actions in code, run as an autoload.
##
## Actions are defined here instead of hand-edited into project.godot's
## [input] block, matching the rest of the project: scene structure is
## generated by build_diorama.gd rather than hand-written resource ids, and
## this keeps the input map reviewable the same way. Autoloads initialize
## before any scene's _ready(), so the actions already exist both for real
## keyboard play and for a demo driving the player via Input.action_press().

const BINDINGS := {
	"move_left": [KEY_A, KEY_LEFT],
	"move_right": [KEY_D, KEY_RIGHT],
	"move_up": [KEY_W, KEY_UP],
	"move_down": [KEY_S, KEY_DOWN],
	"battle_move_1": [KEY_1],
	"battle_move_2": [KEY_2],
	"battle_swap": [KEY_3],
	"battle_target_front": [KEY_F],
	"battle_target_back": [KEY_B],
	"battle_charge": [KEY_C],
}


func _init() -> void:
	for action: String in BINDINGS:
		if InputMap.has_action(action):
			continue
		InputMap.add_action(action)
		for keycode: Key in BINDINGS[action]:
			var ev := InputEventKey.new()
			ev.physical_keycode = keycode
			InputMap.action_add_event(action, ev)
