extends SceneTree
## The combat suite: M3's fifth box.
##
##   godot --headless --path game --script res://tests/run_tests.gd
##
## Invoked by farm/test.py, which is the loop's own runner because the loop may
## not edit farm/verify.sh — see design/combat_tests.md on why that is a
## discipline rather than a gate, and on why there is no third-party framework
## here. What is actually needed is a counter, a comparison and a non-zero exit.
##
## Every expected value is read from design/proto/combat_cases.json, which is
## generated by design/proto/gen_test_cases.py out of the same model that
## settled the balance work. Nothing in this file states a number. That matters
## because three constants are under a live proposal in
## design/first_blood_balance.md: when they move, the fixture is regenerated and
## this suite keeps meaning what it meant, instead of a hundred hand-written
## expectations all going stale at once.
##
## All three tiers of that document run here. Tier 1 is the rules, against
## classes built to be testable without a scene: CombatResolver is pure static
## methods, TypeChart and CreatureDB parse a file and answer lookups, TurnQueue
## tracks order and nothing else. Tier 2 plays seven scripted lines to the end
## of the fight (see PolicyBattery) and checks the winner and the decision count
## against what the model produced. Tier 3 replays one whole fight event for
## event.
##
## A case naming an encounter the engine cannot load — the_ridge, whose
## creatures are designed but unstatted in game/data — is reported as skipped
## rather than omitted, because the failure this suite is most likely to cause
## is somebody reading a green line and believing a check ran.

const CASES := "res://../design/proto/combat_cases.json"

var _passed := 0
var _failed := 0
var _current := ""


func _initialize() -> void:
	var cases := _load_cases()
	if cases.is_empty():
		print("tests: could not read %s" % CASES)
		quit(2)
		return

	_constants(cases)
	_resolver_damage(cases)
	_guard_effectiveness(cases)
	_breaks_defender(cases)
	_type_chart(cases)
	_turn_queue(cases)
	_apply_rules()
	_outcomes(cases)
	_golden_trace(cases)

	print("")
	for note in _skips:
		print("tests: SKIPPED %s" % note)
	if not _skips.is_empty():
		print("")
	if _failed == 0:
		print("tests: %d passed" % _passed)
	else:
		print("tests: %d passed, %d FAILED" % [_passed, _failed])
	quit(1 if _failed > 0 else 0)


var _skips: Array[String] = []


func _playable(encounter_id: String, encounters: EncounterDB) -> bool:
	if encounters.has(encounter_id):
		return true
	return false


func _load_cases() -> Dictionary:
	# res:// cannot walk above the project directory, so resolve the real path.
	var path := ProjectSettings.globalize_path("res://").path_join("../design/proto/combat_cases.json")
	var raw := FileAccess.get_file_as_string(path)
	if raw == "":
		return {}
	return JSON.parse_string(raw)


## ---- Assertions ----

func _section(name: String) -> void:
	_current = name


func _eq(what: String, got: Variant, want: Variant) -> void:
	if typeof(got) == TYPE_FLOAT or typeof(want) == TYPE_FLOAT:
		if is_equal_approx(float(got), float(want)):
			_passed += 1
			return
	elif got == want:
		_passed += 1
		return
	_failed += 1
	print("  FAIL %s: %s — got %s, expected %s" % [_current, what, got, want])


## ---- Tier 1 ----

## The fixture records the constants it was generated against. If they have
## moved in combat_resolver.gd and the fixture has not been regenerated, every
## damage case below is testing arithmetic nobody ships, so check it first and
## say so in those terms.
func _constants(cases: Dictionary) -> void:
	_section("constants")
	var want: Dictionary = cases["constants"]
	_eq("FRONT_DAMAGE_BONUS", CombatResolver.FRONT_DAMAGE_BONUS, want["FRONT_DAMAGE_BONUS"])
	_eq("BACK_TARGET_MULTIPLIER", CombatResolver.BACK_TARGET_MULTIPLIER, want["BACK_TARGET_MULTIPLIER"])
	_eq("CHARGE_MULTIPLIER", CombatResolver.CHARGE_MULTIPLIER, want["CHARGE_MULTIPLIER"])
	_eq("BROKEN_TAKES_MORE_DAMAGE", CombatResolver.BROKEN_TAKES_MORE_DAMAGE, want["BROKEN_TAKES_MORE_DAMAGE"])
	_eq("RESIST_HEAL", CombatResolver.RESIST_HEAL, want["RESIST_HEAL"])


func _resolver_damage(cases: Dictionary) -> void:
	_section("resolver damage")
	for c in cases["resolver_damage"]:
		var defender := _dummy(c["defender_slot"], 99, 3)
		defender.broken = c["defender_broken"]
		var move := {"power": c["move_power"], "category": c["move_category"]}
		var r := CombatResolver.resolve(
			c["attacker_slot"], defender, move, "neutral", c["charge_spent"])
		_eq(c["arithmetic"], r.hp_damage, c["expect_hp_damage"])


func _guard_effectiveness(cases: Dictionary) -> void:
	_section("guard and effectiveness")
	for c in cases["guard_effectiveness"]:
		var defender := _dummy("front", 99, 3)
		var move := {"power": 8, "category": "melee"}
		var r := CombatResolver.resolve("front", defender, move, c["effectiveness"], false)
		_eq("%s guard damage" % c["effectiveness"], r.guard_damage, c["expect_guard_damage"])
		_eq("%s heal" % c["effectiveness"], r.heal, c["expect_heal"])


func _breaks_defender(cases: Dictionary) -> void:
	_section("breaks_defender")
	for c in cases["breaks_defender"]:
		# guard_damage is not settable directly — it comes out of effectiveness,
		# which is the honest way to drive this: a case that cannot be reached
		# through the real API is not a case the game can be in.
		var eff := _effectiveness_for_guard_damage(c["guard_damage"])
		var defender := _dummy("front", 99, maxi(1, c["defender_guard"]))
		defender.guard = c["defender_guard"]
		defender.broken = c["defender_broken"]
		var move := {"power": 8, "category": "melee"}
		var r := CombatResolver.resolve("front", defender, move, eff, false)
		_eq("%d guard damage vs guard %d%s" % [c["guard_damage"], c["defender_guard"],
			" (already broken)" if c["defender_broken"] else ""],
			r.breaks_defender, c["expect_breaks"])


func _effectiveness_for_guard_damage(amount: int) -> String:
	for key in CombatResolver.GUARD_DAMAGE_BY_EFFECTIVENESS:
		if CombatResolver.GUARD_DAMAGE_BY_EFFECTIVENESS[key] == amount:
			return key
	return "neutral"


func _type_chart(cases: Dictionary) -> void:
	_section("type chart")
	var chart := TypeChart.new()
	for c in cases["type_chart"]:
		_eq("%s -> %s" % [c["attacker"], c["defender"]],
			chart.effectiveness(c["attacker"], c["defender"]), c["expect"])


func _turn_queue(cases: Dictionary) -> void:
	_section("turn queue")
	var spec: Dictionary = cases["turn_queue"]
	var queue := TurnQueue.new()
	for i in range(spec["speeds"].size()):
		queue.add_combatant("c%d" % i, "C%d" % i, "player", float(spec["speeds"][i]))
	for i in range(spec["speeds"].size()):
		_eq("initial schedule of c%d" % i, queue.combatants[i].scheduled_time,
			float(spec["expect_initial_scheduled"][i]))

	# preview(n) must return what advance() would, and must not mutate: taken
	# together these are the whole contract the on-screen queue strip rests on.
	var want: Array = spec["expect_advance_order"]
	var previewed: Array[String] = []
	for c in queue.preview(want.size()):
		previewed.append(c.id)
	for i in range(want.size()):
		_eq("preview()[%d]" % i, previewed[i], "c%d" % int(want[i]))
	for i in range(spec["speeds"].size()):
		_eq("preview() left c%d's schedule alone" % i, queue.combatants[i].scheduled_time,
			float(spec["expect_initial_scheduled"][i]))
	for i in range(want.size()):
		_eq("advance()[%d]" % i, queue.advance().id, "c%d" % int(want[i]))


## The one section with no fixture behind it, because these are invariants
## rather than tuned values: design/combat_tests.md states them as properties of
## apply(), and a generator would have to restate the same clamps to produce
## them.
func _apply_rules() -> void:
	_section("apply")
	var d := _dummy("front", 30, 2)

	var r := CombatResolver.resolve("front", d, {"power": 8, "category": "melee"}, "weak", false)
	CombatResolver.apply(d, r)
	_eq("guard floors at 0 rather than going negative", d.guard, 0)
	_eq("a hit that empties Guard Breaks", d.broken, true)

	var full := _dummy("front", 30, 2)
	var heal := CombatResolver.resolve("back", full, {"power": 0, "category": "melee"}, "resist", false)
	CombatResolver.apply(full, heal)
	_eq("a resist heal does not overheal a full-HP defender", full.hp, 30)

	var frail := _dummy("front", 5, 2)
	var big := CombatResolver.resolve("front", frail, {"power": 99, "category": "melee"}, "neutral", false)
	CombatResolver.apply(frail, big)
	_eq("HP clamps at 0 rather than going negative", frail.hp, 0)
	_eq("defeated is set exactly when HP reaches 0", frail.defeated, true)


## ---- Tier 2: whole fights ----

## Plays each scripted line to the end and checks who won and how many decisions
## it took. These are the assertions that keep M3's fourth box true once it is
## ticked: naive must lose, correct targeting must win, and correct targeting
## that hoards its Charges must lose — the last one being what separates "the
## Break/Charge economy matters" from "it exists".
func _outcomes(cases: Dictionary) -> void:
	_section("outcomes")
	var encounters := EncounterDB.new()
	var db := CreatureDB.new()
	var unplayable := {}
	for c in cases["outcomes"]:
		var eid: String = c["encounter"]
		if not encounters.has(eid):
			unplayable[eid] = unplayable.get(eid, 0) + 1
			continue
		var core := BattleCore.new(encounters.team(eid, db), db)
		var played := _play(core, c["line"])
		_eq("%s / %s winner" % [eid, c["line"]], played["winner"], c["expect_winner"])
		_eq("%s / %s decisions" % [eid, c["line"]], played["decisions"],
			c["expect_player_decisions"])
	for eid in unplayable:
		_skips.append("%d outcome cases for %s — it is not in game/data/encounters.json "
			% [unplayable[eid], eid]
			+ "(its creatures have no stats there yet), so the engine cannot play it")


const MAX_TURNS := 400


## The driver, matching combat_solver.py's play(): run the fight forward, hand
## every player turn to the policy, and fall back to a plain melee if the policy
## asks for something illegal — which still costs the decision, because the
## model counts it.
func _play(core: BattleCore, policy: String, events: Array = []) -> Dictionary:
	var db := CreatureDB.new()
	var decisions := 0
	var turns := 0
	while not core.battle_over and turns < MAX_TURNS:
		turns += 1
		var turn: BattleCore.TurnStart = core.start_turn()
		if turn.log_line != "":
			events.append({"kind": "skip", "who": turn.state.display_name})
			continue
		if turn.state == null or turn.state.defeated:
			continue
		if not turn.needs_player_input:
			_record(core, events, turn.state, core.enemy_act(turn.state))
			continue

		var action := PolicyBattery.choose(policy, core, turn.state, decisions)
		decisions += 1
		if action["kind"] == "swap":
			core.swap(turn.state.id)
			continue
		var move: Dictionary = db.get_move(
			turn.state.move_ids[0] if action["melee"] else turn.state.move_ids[1])
		var target := core.pick_target(turn.state, move, action["slot"])
		if target == null:
			move = db.get_move(turn.state.move_ids[0])
			target = core.pick_target(turn.state, move)
		if target == null:
			break
		var charge: bool = action["charge"] and core.charge[turn.state.side] > 0
		_record(core, events, turn.state, core.resolve_and_apply(
			turn.state, target, move, charge), target, move)
	var winner := ""
	if core.is_side_defeated("enemy"):
		winner = "player"
	elif core.is_side_defeated("player"):
		winner = "enemy"
	return {"winner": winner, "decisions": decisions, "turns": turns}


## resolve_and_apply() returns the log line, not the Result, so the structured
## event is rebuilt from the states afterwards. Only the fields both the model
## and the engine can produce are recorded — see the note on STRUCTURED in
## combat_solver.py about why this is compared instead of the format string.
func _record(core: BattleCore, events: Array, actor: CombatantState, line: String,
		target: CombatantState = null, move: Dictionary = {}) -> void:
	if target == null:
		# An enemy turn: recover the defender from the log line it produced.
		for id in core.states:
			var s: CombatantState = core.states[id]
			if s.side != actor.side and line.contains(" on %s " % s.display_name):
				target = s
				break
	if target == null:
		return
	events.append({
		"kind": "attack",
		"attacker": actor.display_name,
		"move": move.get("display_name", _move_name_from(line)),
		"defender": target.display_name,
		"hp": target.hp, "guard": target.guard,
		"breaks": line.contains("is Broken!"),
		"charge_spent": line.contains("(Charge spent!)"),
	})


func _move_name_from(line: String) -> String:
	var a := line.find(" used ")
	var b := line.find(" on ")
	return line.substr(a + 6, b - a - 6) if a >= 0 and b > a else ""


## ---- Tier 3: one whole fight, event for event ----

func _golden_trace(cases: Dictionary) -> void:
	_section("golden trace")
	var spec: Dictionary = cases["golden_trace"]
	var encounters := EncounterDB.new()
	if not encounters.has(spec["encounter"]):
		_skips.append("the golden trace — %s is not in game/data/encounters.json" % spec["encounter"])
		return
	var db := CreatureDB.new()
	var core := BattleCore.new(encounters.team(spec["encounter"], db), db)
	var events: Array = []
	var played := _play(core, spec["policy"], events)
	_eq("winner", played["winner"], spec["winner"])
	_eq("player decisions", played["decisions"], spec["player_decisions"])

	var want: Array = spec["structured_events"]
	_eq("event count", events.size(), want.size())
	for i in range(mini(events.size(), want.size())):
		var got: Dictionary = events[i]
		var exp: Dictionary = want[i]
		var where := "event %d" % (i + 1)
		_eq("%s kind" % where, got["kind"], exp["kind"])
		if exp["kind"] == "skip":
			_eq("%s who" % where, got["who"], exp["who"])
			continue
		_eq("%s attacker" % where, got["attacker"], exp["attacker"])
		_eq("%s move" % where, got["move"], exp["move"])
		_eq("%s defender" % where, got["defender"], exp["defender"])
		_eq("%s defender HP after" % where, got["hp"], exp["defender_hp"])
		_eq("%s defender Guard after" % where, got["guard"], exp["defender_guard"])
		_eq("%s breaks" % where, got["breaks"], exp["breaks"])
		_eq("%s charge spent" % where, got["charge_spent"], exp["charge_spent"])


func _dummy(slot: String, max_hp: int, max_guard: int) -> CombatantState:
	return CombatantState.new("T", "Test", "enemy", slot, "Ember", 10.0,
		max_hp, max_guard, ["ember_bite", "cinder_spray"])
